title: Anahita Azam
description: Economist | Computational Social Scientist | Data Enthusiast
location: Toronto, Canada
email: ana.azam@alumni.utoronto.ca
github: https://github.com/anaazam
linkedin: https://www.linkedin.com/in/anahita-azam/


